# Generated by Django 4.2 on 2024-02-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous',
            name='email',
        ),
        migrations.RemoveField(
            model_name='previous',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='previous',
            name='var',
        ),
    ]
